version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dsgn-app
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_database 
    environment:
      MYSQL_ROOT_PASSWORD: diamond404
      MYSQL_DATABASE: localhost
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: diamond404
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
    driver: local
